### ISSUE TITLE
NvimTree: bad diagnostics symbols highlight

### ISSUE THREAD

**Issue by xeluxee** [sainnhe/edge#38] opened 2021-11-09 21:05 UTC
### Operating system/version

linux

### Terminal emulator/version

kitty

### $TERM environment variable

xterm-kitty

### Feature matrix

not related

### Minimal vimrc that can reproduce this bug.

Simply install edge

### Steps to reproduce this bug using minimal vimrc

1. Open a file and wait for neovim builtin LSP to start
2. Type something (some errors) to make diagnostics arise
3. Open NvimTree buffer `:NvimTreeFindFile`
4. Look at the diagnostics symbol near the file name

### Expected behavior

This screenshot is taken while using [material.nvim](https://github.com/marko-cerovac/material.nvim), and it shows the correct behavior

![error-material](https://user-images.githubusercontent.com/88047141/141004260-6a4f691a-90e7-47be-9708-6913bc69f493.png)

### Actual behavior

This screenshot is taken while using edge

![error-edge](https://user-images.githubusercontent.com/88047141/141004387-efad544c-3e7a-401a-bf0e-8e86349d3694.png)

As you can see error symbol is undercurled and not red

**Comment by sainnhe** [comment] 2021-11-10 08:44
Please provide minimal vimrc next time, I don't use nvim-tree and nvim-lspconfig and my config can't reproduce your bug.

**Comment by sainnhe** [comment] 2021-11-10 08:46
![Screenshot_20211110_164617](https://user-images.githubusercontent.com/37491630/141080073-8318bbb0-1c92-48da-8807-0309327a3e52.png)

I can't reproduce.

**Comment by xeluxee** [comment] 2021-11-10 17:31
> Please provide minimal vimrc next time, I don't use nvim-tree and nvim-lspconfig and my config can't reproduce your bug.

Sorry I thought it wasn't strictly necessary


> I can't reproduce.

You should enable diagnostics in `setup` function:
``` lua
require'nvim-tree'.setup {
  diagnostics = {
    enable = true,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    }
  },
}
```

I think #39 should solve it

**Comment by xeluxee** [comment] 2021-11-10 17:33
> ![Screenshot_20211110_164617](https://user-images.githubusercontent.com/37491630/141080073-8318bbb0-1c92-48da-8807-0309327a3e52.png)

Offtopic, what font are you using here?

**Comment by sainnhe** [comment] 2021-11-11 06:02
Fixed via https://github.com/sainnhe/edge/commit/8540e798b01fd6a3c80ffa4a1930d9733e294b34

---

The font is operator mono.

**Closed by sainnhe** 2021-11-11 06:02 UTC
Labels: bug, cant reproduce, not follow template
